language: ruby
rvm:
- 2.2.5
deploy:
  provider: heroku
  api_key:
    secure: oh8vIJAjhlnMyil7C6cfkD24eg1ABnvvCn2gjI2gburpLQ638bWQTfhh3VJHvvKDBv0j0elggc8coMNDu4kIB6EOzSx/rKELUugGURUX89+o7VW0Q5xkz+kqJrz/7QMiRSHWq7zVgxM5Of5B6gqpNQ+UAljaq2ReHZdrop/CvKib1glXz9t9pWCsJPuirqiRX4TaWYFKYMATSuynPPs2zMtn8gguATCKe1QvGJ59wf/mbn9vgIXambbCmEkejVC6FpVs5EpiG7zKdHncYEyBM2YDx7diqlGI46mMni+kXVHRH8gFy1kErEwEYgdR+D2LzjAsBns4Fik+RNDx1LfZJRTKE6QMEBSV63qOLG4LL36KoMnwqjtlA6UDFTvCd2lmmTOe6iSbGA7Xq9RP+y3/FXO0GxvptleCfLEIlr2BNuJp52LbRfLyUf30+pbYMmSfTsHqZUpjWDGO30u6WZNCd3JvCJfYo0XGTcamoD1ebIHjAkLjqTZcglwmHbdyRL01gILrjrNfl1zaix97pf5FtiL7erBgvu11cm3lD9qI4iCjBCusRVQUROVlQX7JxHKGYaScisX05TAHzGilPsRd05ZqG67WpNHB+1464O85eMCls4FXn6AivSAoJKUB9P3oJXkITkPEaH0UqCc3yzZj7hGCC5ze2wqnucS2qewX4uk=
  app: thawing-fjord-31597
  on:
    repo: cloudliner/rakuten_enpit_example
